FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

COPY *.sln .
COPY *.csproj .
RUN dotnet restore 

COPY . ./demo_api/
WORKDIR /source/demo_api
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-amd64
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "demo_api_nohttps.dll"]